[tools]

awscli = "latest"
cargo-binstall = "latest"
delta = "latest"
direnv = "latest"
java = "latest"
k9s = "latest"
kubectl = "latest"
lua-language-server = "latest"
minikube = "latest"
neovim = "nightly"
nodejs = "22.13.1"
python = ["3.12.3", "3.11.4", "3.13.1"]
ripgrep = "latest"
sqlite = "latest"
terraform = "latest"
terraform-ls = "latest"
yarn = "1.22.22"
"npm:bash-language-server" = "latest"
"npm:svelte-language-server" = "latest"
"npm:prettier" = "latest"
"npm:prettier-plugin-svelte" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vim-language-server" = "latest"
"pipx:basedpyright" = "latest"
"pipx:grip" = "latest"
"pipx:poetry" = { version = "latest", uvx_args = "--with poetry-plugin-export" }
