alias tmux='tmux -2'
alias tl='tmux ls'
alias tn='tmux new -s'
alias ta='tmux attach -t'
alias tk='tmux kill-session -t'

alias vn='virtualenv -p python3 venv'
alias va='source venv/bin/activate'

include () {
  [[ -f "$1" ]] && source "$1"
}

LOCALPATH=~/.bashrc_local
include $LOCALPATH

