#!/usr/bin/python3

from datetime import datetime
import subprocess
import os

COMMAND = 'xdg-open'
URL = 'https://keplergroup.harvestapp.com/time/week'

if datetime.now().weekday() in {0, 1, 4}: # run mon, tues, fri
    my_env = os.environ.copy()
    my_env["DISPLAY"] = ':0'
    process = subprocess.Popen([COMMAND, URL], env=my_env)
    process.wait(timeout=30)
