#!/usr/bin/python3

import subprocess
import os

COMMAND = 'xdg-open'
URL = 'https://keplergroup.harvestapp.com/time/week'

my_env = os.environ.copy()
my_env["DISPLAY"] = ':0'
process = subprocess.Popen([COMMAND, URL], env=my_env)
process.wait(timeout=30)
