require('nvim-treesitter.configs').setup({
  highlight = { enable = true },
  indent = { enable = true },
  ensure_installed = {
    'css',
    'dockerfile',
    'bash',
    'graphql',
    'html',
    'javascript',
    'rust',
    'tsx',
    'svelte',
    'scss',
    'json',
    'jsdoc',
    'typescript',
    'query',
    'markdown',
    'mermaid',
  },
})
